### ISSUE TITLE
Código de uso das estrategias.

### ISSUE THREAD

**Issue by Throtikbr** [gustavonovaes/blaze-double-roulette-crawler#1]
Gostaria de saber como usa as estratégias.

**Comment by gustavonovaes** [comment]
O código das estratégias é de um outro projeto e acabou subindo por engano junto com a lib 😅

Mas basicamente, é um conjunto de objetos que contém o padrão esperado nos últimos 6 resultados da roleta e quando for correspondente, sugere qual será próximo resultado a partir daquele padrão.

A estratégia era algo parecido com o exemplo abaixo, onde `roulette` contém o padrão esperado na roleta, `expected` é o próximo resultado esperado e `text` monta a string que será informada para o usuário (no meu caso, via Telegram). 

```js
{
  roulette: ['black', 'black', 'black', 'black', 'black', 'black'],
  expected: ['red', 'white'],
  text: () => {
    return [
      "💰 Entrar no 🟥 VERMELHO",
      "🛡 Cobrir no ⬜ BRANCO",'
    ].join("\n");
  }
}
```

Nesse caso, ele sugere que o usuário aposte no Vermelho e também no Branco. 

Pelos meus testes, o resultado de cada estratégia muda bastante ao longo do dia, mas tem algumas estratégias que no geral dão bem certo (taxa de acerto maior que 70~80%). É importante também considerar o [Martingale](https://pt.wikipedia.org/wiki/Martingale).
